import { useState } from "react";
import { Bike, Wrench, Users, AlertTriangle, TrendingUp, Activity, Clock, CheckCircle, Calendar, MapPin, ShieldCheck, Zap } from "lucide-react";
import { Card, StatCard, Badge, StatusBadge } from "../components/ui.jsx";
import { computePmStatus, PmStatusBadge } from "../lib/pm-engine.jsx";

// ─── Dashboard ───────────────────────────────────────────────────────
export function Dashboard({ db }) {
  const totalBikes = db.bicycles.length;
  const totalClients = db.clients.length;
  const scheduledMaint = db.workOrders.filter(wo => wo.status !== "resolved").length;
  const totalTools = db.tools.reduce((sum, t) => sum + t.quantity, 0);
  const toolValue = db.tools.reduce((sum, t) => sum + t.cost * t.quantity, 0);
  const tripDaysUntil = Math.ceil((new Date(db.grantTrip.travel.departureDate) - new Date()) / (1000 * 60 * 60 * 24));
  const checklistDone = db.grantTrip.checklist.filter(c => c.done).length;
  const checklistTotal = db.grantTrip.checklist.length;

  // Compute fleet health for all bikes
  const fleetHealth = db.bicycles.map(bike => ({
    bike,
    client: db.clients.find(c => c.id === bike.clientId),
    pm: computePmStatus(bike, db.workOrders),
  }));

  const greenCount = fleetHealth.filter(f => f.pm.status === "green").length;
  const yellowCount = fleetHealth.filter(f => f.pm.status === "yellow").length;
  const redCount = fleetHealth.filter(f => f.pm.status === "red").length;

  // Sort: red first, then yellow, then green
  const sortedFleet = [...fleetHealth].sort((a, b) => {
    const order = { red: 0, yellow: 1, green: 2 };
    return (order[a.pm.status] ?? 3) - (order[b.pm.status] ?? 3);
  });

  const recentMaint = [...db.maintenance].sort((a, b) => new Date(b.scheduledDate) - new Date(a.scheduledDate)).slice(0, 5);
  const activeWOs = db.workOrders.filter(wo => wo.status !== "resolved").sort((a, b) => {
    const pOrd = { urgent: 0, high: 1, normal: 2, low: 3 };
    return (pOrd[a.priority] ?? 4) - (pOrd[b.priority] ?? 4);
  }).slice(0, 6);
  const autoGenCount = db.workOrders.filter(wo => wo._autoGenerated && wo.status === "new").length;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Dashboard</h1>
        <p className="text-sm text-gray-500 mt-1">Lānaʻi Estate Stewardship - Bicycle Program</p>
      </div>
      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">
        <StatCard icon={Bike} label="Bicycles" value={totalBikes} color="blue" />
        <StatCard icon={Users} label="Properties" value={totalClients} color="purple" />
        <StatCard icon={Calendar} label="Active WOs" value={scheduledMaint} sub="work orders open" color="yellow" />
        <StatCard icon={Wrench} label="Tools" value={totalTools} sub={`$${toolValue.toLocaleString()} invested`} color="green" />
        <StatCard icon={MapPin} label="UBI Trip" value={tripDaysUntil > 0 ? `${tripDaysUntil}d` : "Now!"} sub="until departure" color="orange" />
        <StatCard icon={CheckCircle} label="Trip Prep" value={`${checklistDone}/${checklistTotal}`} sub="checklist items" color="teal" />
      </div>

      {/* Fleet Health Traffic Light */}
      <Card className="p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-gray-900 flex items-center gap-2">
            <ShieldCheck size={18} /> Fleet Health
          </h3>
          <div className="flex items-center gap-3 text-sm">
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full bg-green-500" />
              <span className="font-medium text-gray-700">{greenCount}</span>
              <span className="text-gray-400">ready</span>
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full bg-yellow-500" />
              <span className="font-medium text-gray-700">{yellowCount}</span>
              <span className="text-gray-400">attention</span>
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-500" />
              <span className="font-medium text-gray-700">{redCount}</span>
              <span className="text-gray-400">action needed</span>
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-3">
          {sortedFleet.map(({ bike, client, pm }) => {
            const borderColor = pm.status === "red" ? "border-red-300 bg-red-50/40" : pm.status === "yellow" ? "border-yellow-300 bg-yellow-50/40" : "border-green-200 bg-green-50/30";
            const dotColor = pm.status === "red" ? "bg-red-500" : pm.status === "yellow" ? "bg-yellow-500" : "bg-green-500";
            return (
              <div key={bike.id} className={`border rounded-lg p-3 ${borderColor}`}>
                <div className="flex items-start gap-2 mb-1">
                  <span className={`w-2.5 h-2.5 rounded-full shrink-0 mt-1 ${dotColor}`} />
                  <span className="text-sm font-semibold text-gray-900 leading-snug">
                    {bike.nickname || `${bike.make} ${bike.model}`}
                  </span>
                </div>
                <p className="text-xs text-gray-500">{bike.type} | {client?.name || "---"}</p>
                {pm.daysSinceService !== null && (
                  <p className="text-xs text-gray-400 mt-1">{pm.daysSinceService}d since service | {pm.rideDaysSinceLastPM} ride-days</p>
                )}
                {pm.status !== "green" && pm.reason && (
                  <p className="text-xs text-gray-600 mt-0.5">{pm.reason}</p>
                )}
                {pm.nextDueDate && pm.status !== "green" && (
                  <p className="text-xs text-gray-400">Due: {pm.nextDueDate}</p>
                )}
              </div>
            );
          })}
        </div>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="p-5">
          <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <Activity size={18} /> Active Work Orders
            {autoGenCount > 0 && (
              <span className="ml-auto inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-700">
                <Zap size={12} /> {autoGenCount} auto-generated
              </span>
            )}
          </h3>
          {activeWOs.length === 0 ? <p className="text-sm text-gray-500">No active work orders.</p> : (
            <div className="space-y-3">
              {activeWOs.map(wo => {
                const bike = db.bicycles.find(b => b.id === wo.bicycleId);
                const priorityColors = { urgent: "text-red-600", high: "text-orange-600", normal: "text-blue-600", low: "text-gray-500" };
                return (
                  <div key={wo.id} className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <p className="text-sm font-medium text-gray-900 truncate">{wo.description?.slice(0, 50) || wo.type}{wo.description?.length > 50 ? "..." : ""}</p>
                        {wo._autoGenerated && <Zap size={12} className="text-blue-500 shrink-0" title="Auto-generated PM" />}
                      </div>
                      <p className="text-xs text-gray-500">{bike ? (bike.nickname || bike.make + " " + bike.model) : "Unknown"} | <span className={priorityColors[wo.priority] || ""}>{wo.priority}</span> | {wo.scheduledDate}</p>
                    </div>
                    <StatusBadge status={wo.status} />
                  </div>
                );
              })}
            </div>
          )}
        </Card>

        <Card className="p-5">
          <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2"><MapPin size={18} /> Grant's UBI Trip Status</h3>
          <div className="space-y-3">
            <div className="flex justify-between text-sm"><span className="text-gray-600">Status</span><StatusBadge status={db.grantTrip.status} /></div>
            <div className="flex justify-between text-sm"><span className="text-gray-600">Departure</span><span className="font-medium">{db.grantTrip.travel.departureDate}</span></div>
            <div className="flex justify-between text-sm"><span className="text-gray-600">Courses Enrolled</span><span className="font-medium">{db.grantTrip.courses.filter(c => c.status === "enrolled").length}/{db.grantTrip.courses.length}</span></div>
            <div className="mt-3">
              <p className="text-xs text-gray-500 mb-1.5">Preparation Progress</p>
              <div className="w-full bg-gray-200 rounded-full h-2.5">
                <div className="bg-blue-600 h-2.5 rounded-full transition-all" style={{ width: `${(checklistDone / checklistTotal) * 100}%` }} />
              </div>
              <p className="text-xs text-gray-500 mt-1">{checklistDone} of {checklistTotal} tasks complete</p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}

