import { useState } from "react";
import {
  Bike, Wrench, Users, AlertTriangle, Activity, Clock, CheckCircle,
  Calendar, MapPin, ShieldCheck, Zap, Package, ShoppingCart, CalendarCheck,
  Droplets, Plus, ChevronDown, ChevronRight, MapPinned
} from "lucide-react";
import { Card, StatCard, Badge, StatusBadge, Button } from "../components/ui.jsx";
import { computePmStatus } from "../lib/pm-engine.jsx";

// ─── Dashboard ───────────────────────────────────────────────────────
export function Dashboard({ db, onNavigate, perms }) {
  const totalBikes = db.bicycles.length;
  const totalClients = db.clients.length;
  const activeWOCount = db.workOrders.filter(wo => wo.status !== "resolved").length;
  const totalTools = db.tools.reduce((sum, t) => sum + t.quantity, 0);
  const toolValue = db.tools.reduce((sum, t) => sum + t.cost * t.quantity, 0);

  // Inventory alerts
  const lowStockParts = (db.parts || []).filter(p => p.currentStock <= p.reorderThreshold);
  const lowStockSupplies = (db.supplies || []).filter(s => s.currentStock <= s.reorderThreshold);
  const lowStockTotal = lowStockParts.length + lowStockSupplies.length;
  const pendingPRs = (db.purchaseRequests || []).filter(pr => pr.status === "pending" || pr.status === "manager_approved");
  const toolsAtProperties = db.tools.filter(t => t.currentPropertyId !== null);

  // Fleet health
  const fleetHealth = db.bicycles.map(bike => ({
    bike,
    client: db.clients.find(c => c.id === bike.clientId),
    pm: computePmStatus(bike, db.workOrders),
  }));
  const greenCount = fleetHealth.filter(f => f.pm.status === "green").length;
  const yellowCount = fleetHealth.filter(f => f.pm.status === "yellow").length;
  const redCount = fleetHealth.filter(f => f.pm.status === "red").length;
  const attentionFleet = [...fleetHealth]
    .filter(f => f.pm.status !== "green")
    .sort((a, b) => {
      const order = { red: 0, yellow: 1 };
      return (order[a.pm.status] ?? 2) - (order[b.pm.status] ?? 2);
    });

  // Active work orders (top 6 by priority)
  const activeWOs = db.workOrders.filter(wo => wo.status !== "resolved").sort((a, b) => {
    const pOrd = { urgent: 0, high: 1, normal: 2, low: 3 };
    return (pOrd[a.priority] ?? 4) - (pOrd[b.priority] ?? 4);
  }).slice(0, 6);
  const autoGenCount = db.workOrders.filter(wo => wo._autoGenerated && wo.status === "new").length;

  // Active bookings (top 5)
  const activeBookings = (db.bookings || [])
    .filter(bk => ["pending", "confirmed", "active"].includes(bk.status))
    .sort((a, b) => new Date(a.startDate) - new Date(b.startDate))
    .slice(0, 5);

  // Recent resolved WOs (top 5)
  const recentResolved = db.workOrders
    .filter(wo => wo.status === "resolved")
    .sort((a, b) => new Date(b.completedDate || b.scheduledDate) - new Date(a.completedDate || a.scheduledDate))
    .slice(0, 5);

  // Grant's trip — collapsible
  const tripDaysUntil = Math.ceil((new Date(db.grantTrip.travel.departureDate) - new Date()) / (1000 * 60 * 60 * 24));
  const checklistDone = db.grantTrip.checklist.filter(c => c.done).length;
  const checklistTotal = db.grantTrip.checklist.length;
  const [tripOpen, setTripOpen] = useState(tripDaysUntil <= 30);

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Dashboard</h1>
        <p className="text-sm text-gray-500 mt-1">Lānaʻi Estate Stewardship - Bicycle Program</p>
      </div>

      {/* ── Stat Cards ── */}
      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">
        <StatCard icon={Bike} label="Bicycles" value={totalBikes} color="blue" />
        <StatCard icon={Users} label="Properties" value={totalClients} color="purple" />
        <StatCard icon={Calendar} label="Active WOs" value={activeWOCount} sub="work orders open" color="yellow" />
        <StatCard icon={Wrench} label="Tools" value={totalTools} sub={`$${toolValue.toLocaleString()} invested`} color="green" />
        <StatCard icon={Package} label="Low Stock" value={lowStockTotal} sub={lowStockTotal > 0 ? "items below threshold" : "all stocked"} color={lowStockTotal > 0 ? "red" : "green"} />
        <StatCard icon={ShoppingCart} label="Pending PRs" value={pendingPRs.length} sub={pendingPRs.length > 0 ? "awaiting approval" : "none pending"} color={pendingPRs.length > 0 ? "orange" : "green"} />
      </div>

      {/* ── Quick Actions ── */}
      <div className="flex flex-wrap gap-2">
        <Button variant="secondary" size="sm" onClick={() => onNavigate("workorders")}>
          <Plus size={14} /> New Work Order
        </Button>
        <Button variant="secondary" size="sm" onClick={() => onNavigate("clients")}>
          <Users size={14} /> Clients
        </Button>
        <Button variant="secondary" size="sm" onClick={() => onNavigate("bookings")}>
          <CalendarCheck size={14} /> Bookings
        </Button>
        <Button variant="secondary" size="sm" onClick={() => onNavigate("parts")}>
          <Package size={14} /> Parts
        </Button>
        <Button variant="secondary" size="sm" onClick={() => onNavigate("supplies")}>
          <Droplets size={14} /> Supplies
        </Button>
      </div>

      {/* ── Fleet Health (condensed) ── */}
      <Card className="p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-gray-900 flex items-center gap-2">
            <ShieldCheck size={18} /> Fleet Health
          </h3>
          <div className="flex items-center gap-3 text-sm">
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full bg-green-500" />
              <span className="font-medium text-gray-700">{greenCount}</span>
              <span className="text-gray-400">ready</span>
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full bg-yellow-500" />
              <span className="font-medium text-gray-700">{yellowCount}</span>
              <span className="text-gray-400">attention</span>
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-500" />
              <span className="font-medium text-gray-700">{redCount}</span>
              <span className="text-gray-400">action needed</span>
            </span>
          </div>
        </div>

        {attentionFleet.length === 0 ? (
          <div className="flex items-center gap-2 text-green-700 bg-green-50 rounded-lg p-3">
            <CheckCircle size={18} />
            <span className="text-sm font-medium">All {totalBikes} bikes are healthy — no action needed.</span>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-3">
            {attentionFleet.map(({ bike, client, pm }) => {
              const borderColor = pm.status === "red" ? "border-red-300 bg-red-50/40" : "border-yellow-300 bg-yellow-50/40";
              const dotColor = pm.status === "red" ? "bg-red-500" : "bg-yellow-500";
              return (
                <div key={bike.id} className={`border rounded-lg p-3 ${borderColor}`}>
                  <div className="flex items-start gap-2 mb-1">
                    <span className={`w-2.5 h-2.5 rounded-full shrink-0 mt-1 ${dotColor}`} />
                    <span className="text-sm font-semibold text-gray-900 leading-snug">
                      {bike.nickname || `${bike.make} ${bike.model}`}
                    </span>
                  </div>
                  <p className="text-xs text-gray-500">{bike.type} | {client?.name || "---"}</p>
                  {pm.daysSinceService !== null && (
                    <p className="text-xs text-gray-400 mt-1">{pm.daysSinceService}d since service | {pm.rideDaysSinceLastPM} ride-days</p>
                  )}
                  {pm.reason && (
                    <p className="text-xs text-gray-600 mt-0.5">{pm.reason}</p>
                  )}
                  {pm.nextDueDate && (
                    <p className="text-xs text-gray-400">Due: {pm.nextDueDate}</p>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </Card>

      {/* ── Row: Active WOs + Active Bookings ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Active Work Orders */}
        <Card className="p-5">
          <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <Activity size={18} /> Active Work Orders
            {autoGenCount > 0 && (
              <span className="ml-auto inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-700">
                <Zap size={12} /> {autoGenCount} auto-generated
              </span>
            )}
          </h3>
          {activeWOs.length === 0 ? (
            <p className="text-sm text-gray-500">No active work orders.</p>
          ) : (
            <div className="space-y-3">
              {activeWOs.map(wo => {
                const bike = db.bicycles.find(b => b.id === wo.bicycleId);
                const priorityColors = { urgent: "text-red-600", high: "text-orange-600", normal: "text-blue-600", low: "text-gray-500" };
                return (
                  <div key={wo.id} className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <p className="text-sm font-medium text-gray-900 truncate">{wo.description?.slice(0, 50) || wo.type}{wo.description?.length > 50 ? "..." : ""}</p>
                        {wo._autoGenerated && <Zap size={12} className="text-blue-500 shrink-0" title="Auto-generated PM" />}
                      </div>
                      <p className="text-xs text-gray-500">{bike ? (bike.nickname || bike.make + " " + bike.model) : "Unknown"} | <span className={priorityColors[wo.priority] || ""}>{wo.priority}</span> | {wo.scheduledDate}</p>
                    </div>
                    <StatusBadge status={wo.status} />
                  </div>
                );
              })}
            </div>
          )}
        </Card>

        {/* Active Bookings */}
        <Card className="p-5">
          <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <CalendarCheck size={18} /> Active Bookings
          </h3>
          {activeBookings.length === 0 ? (
            <p className="text-sm text-gray-500">No active bookings.</p>
          ) : (
            <div className="space-y-3">
              {activeBookings.map(bk => {
                const bike = db.bicycles.find(b => b.id === bk.bicycleId);
                const client = db.clients.find(c => c.id === bk.clientId);
                return (
                  <div key={bk.id} className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-gray-900 truncate">
                        {bike ? (bike.nickname || `${bike.make} ${bike.model}`) : "Unknown bike"}
                      </p>
                      <p className="text-xs text-gray-500">
                        {client?.name || "---"} | {bk.startDate} → {bk.endDate}
                      </p>
                    </div>
                    <StatusBadge status={bk.status} />
                  </div>
                );
              })}
            </div>
          )}
        </Card>
      </div>

      {/* ── Row: Inventory Alerts + Approvals & Activity ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Inventory Alerts */}
        <Card className="p-5">
          <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <AlertTriangle size={18} /> Inventory Alerts
          </h3>
          {lowStockParts.length === 0 && lowStockSupplies.length === 0 && toolsAtProperties.length === 0 ? (
            <div className="flex items-center gap-2 text-green-700 bg-green-50 rounded-lg p-3">
              <CheckCircle size={18} />
              <span className="text-sm font-medium">All clear — no inventory alerts.</span>
            </div>
          ) : (
            <div className="space-y-4">
              {/* Low stock parts */}
              {lowStockParts.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Low Stock Parts</p>
                  <div className="space-y-2">
                    {lowStockParts.slice(0, 5).map(p => (
                      <div key={p.id} className="flex items-center justify-between">
                        <span className="text-sm text-gray-900">{p.name}</span>
                        <Badge color="red">{p.currentStock} / {p.reorderThreshold}</Badge>
                      </div>
                    ))}
                    {lowStockParts.length > 5 && <p className="text-xs text-gray-400">+{lowStockParts.length - 5} more</p>}
                  </div>
                </div>
              )}
              {/* Low stock supplies */}
              {lowStockSupplies.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Low Stock Supplies</p>
                  <div className="space-y-2">
                    {lowStockSupplies.slice(0, 5).map(s => (
                      <div key={s.id} className="flex items-center justify-between">
                        <span className="text-sm text-gray-900">{s.name}</span>
                        <Badge color="red">{s.currentStock} / {s.reorderThreshold}</Badge>
                      </div>
                    ))}
                    {lowStockSupplies.length > 5 && <p className="text-xs text-gray-400">+{lowStockSupplies.length - 5} more</p>}
                  </div>
                </div>
              )}
              {/* Tools at properties */}
              {toolsAtProperties.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Tools Checked Out</p>
                  <div className="space-y-2">
                    {toolsAtProperties.slice(0, 5).map(t => {
                      const prop = db.clients.find(c => c.id === t.currentPropertyId);
                      return (
                        <div key={t.id} className="flex items-center justify-between">
                          <span className="text-sm text-gray-900">{t.name}</span>
                          <Badge color="blue">{prop?.name || "Unknown"}</Badge>
                        </div>
                      );
                    })}
                    {toolsAtProperties.length > 5 && <p className="text-xs text-gray-400">+{toolsAtProperties.length - 5} more</p>}
                  </div>
                </div>
              )}
            </div>
          )}
        </Card>

        {/* Pending Approvals + Recent Activity */}
        <Card className="p-5">
          <div className="space-y-6">
            {/* Pending Purchase Requests — gated by perms */}
            {perms?.partsApproveOrder && pendingPRs.length > 0 && (
              <div>
                <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <ShoppingCart size={18} /> Pending Approvals
                </h3>
                <div className="space-y-2">
                  {pendingPRs.slice(0, 5).map(pr => {
                    const part = (db.parts || []).find(p => p.id === pr.partId);
                    return (
                      <div key={pr.id} className="flex items-center justify-between py-1.5 border-b border-gray-100 last:border-0">
                        <div className="min-w-0 flex-1">
                          <p className="text-sm text-gray-900 truncate">{part?.name || pr.partId}</p>
                          <p className="text-xs text-gray-500">Qty: {pr.quantity}</p>
                        </div>
                        <StatusBadge status={pr.status} />
                      </div>
                    );
                  })}
                  {pendingPRs.length > 5 && <p className="text-xs text-gray-400">+{pendingPRs.length - 5} more</p>}
                </div>
              </div>
            )}

            {/* Recent Activity */}
            <div>
              <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                <Clock size={18} /> Recent Activity
              </h3>
              {recentResolved.length === 0 ? (
                <p className="text-sm text-gray-500">No recently resolved work orders.</p>
              ) : (
                <div className="space-y-2">
                  {recentResolved.map(wo => {
                    const bike = db.bicycles.find(b => b.id === wo.bicycleId);
                    return (
                      <div key={wo.id} className="flex items-center justify-between py-1.5 border-b border-gray-100 last:border-0">
                        <div className="min-w-0 flex-1">
                          <p className="text-sm text-gray-900 truncate">{wo.description?.slice(0, 45) || wo.type}{wo.description?.length > 45 ? "..." : ""}</p>
                          <p className="text-xs text-gray-500">{bike ? (bike.nickname || `${bike.make} ${bike.model}`) : "Unknown"} | {wo.completedDate || wo.scheduledDate}</p>
                        </div>
                        <Badge color="green">Resolved</Badge>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </Card>
      </div>

      {/* ── Grant's UBI Trip (collapsible) ── */}
      <Card className="p-5">
        <button
          onClick={() => setTripOpen(o => !o)}
          className="w-full flex items-center justify-between text-left"
        >
          <h3 className="font-semibold text-gray-900 flex items-center gap-2">
            <MapPin size={18} /> Grant's UBI Trip
            <span className="text-sm font-normal text-gray-500">
              — {tripDaysUntil > 0 ? `${tripDaysUntil} days until departure` : "Departing now!"}
            </span>
          </h3>
          {tripOpen ? <ChevronDown size={18} className="text-gray-400" /> : <ChevronRight size={18} className="text-gray-400" />}
        </button>
        {tripOpen && (
          <div className="mt-4 space-y-3">
            <div className="flex justify-between text-sm"><span className="text-gray-600">Status</span><StatusBadge status={db.grantTrip.status} /></div>
            <div className="flex justify-between text-sm"><span className="text-gray-600">Departure</span><span className="font-medium">{db.grantTrip.travel.departureDate}</span></div>
            <div className="flex justify-between text-sm"><span className="text-gray-600">Courses Enrolled</span><span className="font-medium">{db.grantTrip.courses.filter(c => c.status === "enrolled").length}/{db.grantTrip.courses.length}</span></div>
            <div className="mt-3">
              <p className="text-xs text-gray-500 mb-1.5">Preparation Progress</p>
              <div className="w-full bg-gray-200 rounded-full h-2.5">
                <div className="bg-blue-600 h-2.5 rounded-full transition-all" style={{ width: `${(checklistDone / checklistTotal) * 100}%` }} />
              </div>
              <p className="text-xs text-gray-500 mt-1">{checklistDone} of {checklistTotal} tasks complete</p>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}
